[Samples][42.scaleout] Add DialogHost and change of Object to JsonNode
southworks/botbuilder-java pull request #180
Opened 2021-04-05 22:14 UTC by Batta32

Fixes #

## Description

## Specific Changes

  - 
  -
  -

## Testing

2021-04-05 22:28 UTC, fran893 requested changes

2021-04-05 22:28 UTC, fran893 commented on samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHost.java
> +    private static ObjectMapper objectMapper = new ObjectMapper()
You missed this [comment](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/42.scaleout/DialogHost.cs#L24).

2021-04-05 22:28 UTC, fran893 commented on samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHost.java
> +     * The... ummm... logger.
Is this comment ok?

2021-04-06 12:09 UTC, Batta32 commented on samples/42.scaleout/src/main/java/com/microsoft/bot/sample/scaleout/DialogHost.java
> +     * The... ummm... logger.
Yeah, I copied from another sample

2021-04-06 12:29 UTC, fran893 approved these changes

2021-04-06 12:30 UTC, merged